import{S as h,i as b,a as E}from"./assets/vendor-D94OL8Qp.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const i of n.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&s(i)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();let d=null;function c(t){b.show({message:t,position:"topRight",timeout:4e3,backgroundColor:"#EF4040",messageColor:"#FAFAFB",iconUrl:"./assets/icons/close-icon.svg",closeOnClick:!0})}function w(){document.getElementById("gallery").innerHTML=""}function p(t){const o=document.getElementById("gallery");if(t.total===0){c("Нічого не знайдено. Спробуй інше слово.");return}const r=document.createDocumentFragment();t.hits.forEach(s=>{const e=document.createElement("li");e.className="gallery-item",e.innerHTML=`
      <a href="${s.largeImageURL}" class="gallery-link">
        <img src="${s.webformatURL}" alt="${s.tags}" class="gallery-image" />
      </a>
      <div class="gallery-info">
        <p><b>Likes:</b> ${s.likes}</p>
        <p><b>Views:</b> ${s.views}</p>
        <p><b>Comments:</b> ${s.comments}</p>
        <p><b>Downloads:</b> ${s.downloads}</p>
      </div>
    `,r.appendChild(e)}),o.appendChild(r),d?d.refresh():d=new h(".gallery a")}const L="49574533-99195dbfc8ece3e2fce047715",v="https://pixabay.com/api/",I={key:L,image_type:"photo",orientation:"horizontal",safesearch:"true"};let f=1;const B=15;function P(){f=1}function C(){f+=1}async function g(t){const o=document.getElementById("loader");o.style.display="flex";try{return(await E.get(v,{params:{...I,q:t,page:f,per_page:B}})).data}catch(r){throw c("Щось пішло не так 😢"),r}finally{o.style.display="none"}}const x=document.getElementById("searchForm"),u=document.getElementById("searchInput"),A=document.getElementById("gallery"),l=document.createElement("button");l.textContent="Load more";l.className="load-more-btn";l.style.display="none";A.after(l);let m="",y=0,a=0;x.addEventListener("submit",async t=>{t.preventDefault();const o=u.value.trim();if(o){m=o,P(),w(),l.style.display="none";try{const r=await g(m);y=r.totalHits,a=r.hits.length,p(r),a<y?l.style.display="block":c("We're sorry, but you've reached the end of search results.")}catch(r){console.log(r)}u.value="",u.blur()}});l.addEventListener("click",async()=>{C();try{const t=await g(m);a+=t.hits.length,p(t),F(),a>=y&&(l.style.display="none",c("We're sorry, but you've reached the end of search results."))}catch(t){console.log(t)}});function F(){const t=document.querySelector(".gallery-item");if(t){const o=t.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
